_format_version: "1.1"
services:
- name: jwt-test-api
  url: https://example.com/
  routes:
  - paths:
    - "/"
  plugins:
  - name: jwt-wallet
    config:
#      rbac: http://localhost:8888/api/v1/rbac/account/{addr}/grants
      rbac: http://localhost:8888/{addr}/index.html