_format_version: "1.1"
services:
- name: jwt-test-api
  url: https://github.com/jphorec
  routes:
  - paths:
    - "/"
  plugins:
  - name: jwt-wallet
    config:
      rbac: http://host.docker.internal:8080/api/v1/rbac/account/