_format_version: "1.1"
services:
- name: jwt-test-api
  url: https://github.com/jphorec
  routes:
  - paths:
    - "/"
  plugins:
  - name: jwt-wallet
    config:
      network_uri: locoalhost:2000
      rbac_service_uri: localhost:5000