_format_version: "1.1"
services:
- name: jwt-test-api
  url: https://github.com/jphorec
  routes:
  - paths:
    - "/"
  plugins:
  - name: jwt-wallet
    config:
      grpc_url: locoalhost:2000
      roles_url: http://localhost:8080/api/v1/rbac/account/