_format_version: "1.1"
services:
- name: jwt-test-api
  url: https://example.com/
  routes:
  - paths:
    - "/"
  plugins:
  - name: jwt-wallet
    config:
      authHeader: Authorization
      accessHeader: x-wallet-access
      includeSenderHeader: false
#      rbac: http://docker.for.mac.host.internal:8069/rbac/api/v1/subjects/{addr}/grants  # Running RBAC Service on Mac
      rbac: http://localhost:8069/rbac/api/v1/subjects/{addr}/grants                     # Running RBAC Service on Linux
#      rbac: http://docker.for.mac.host.internal:8888/{addr}/index.html                   # Use when running `make http` on Mac
#      rbac: http://localhost:8888/{addr}/index.html                                      # Use when running `make http` on Linux